import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { NoteFooter } from "@/components/NoteFooter";
import { NoteHeader } from "@/components/NoteHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-between flex-col items-center h-screen">
          <NoteHeader />
          <div className="w-full max-w-xl m-auto ">{children}</div>
          <NoteFooter />
        </div>
      </body>
    </html>
  );
}
